thomas-HP-ZBook-14:
  dropbox_dir: "/home/thomas/Dropbox"
dropbox_file: ["daily_notes_dropbox.txt"]
logo: ["figs", "graph_icon.ico"]
fig: ["figs"]
gui: ["gui", "todo_window_gui.ui"]
guimain: ["gui", "task_timer_layout.ui"]
log_add: ["Notebook", "log_files"]
task_config: ["Notebook", "miscellaneous", "task_timer_config.json"]
